language: node_js
sudo: false
dist: trusty
node_js:
  - '6.11.5'

cache:
  yarn: true
  directories:
     - ./node_modules

before_install:
  - "echo -e repo_token: $GITHUB_TOKEN >> $TRAVIS_BUILD_DIR/.coveralls.yml"

before_script:
  - npm install -g codecov
  - npm install -g --silent @angular/cli
  - npm install -g --silent yarn
  - yarn install
  - ng test --watch=false --code-coverage --silent >> /dev/null

script:
  - codecov
  - cat ./coverage/coverage.lcov | ./node_modules/coveralls/bin/coveralls.js
  - npm run lint
  - npm run build:electron
