language: node_js
sudo: true
dist: trusty
node_js:
  - '6.11.5'

cache:
  yarn: true
  directories:
     - ./node_modules

before_install:
  - "echo -e repo_token: $GITHUB_TOKEN >> $TRAVIS_BUILD_DIR/.coveralls.yml"
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g codecov
  - npm install -g --silent @angular/cli
  - npm install -g --silent yarn
  - yarn install
  - ng test --watch=false --code-coverage --silent

script:
  - codecov
  - cat $TRAVIS_BUILD_DIR/coverage/lcov.info | $TRAVIS_BUILD_DIR/node_modules/coveralls/bin/coveralls.js
  - npm run lint
  - npm run build:electron
