language: node_js
sudo: false
dist: trusty
node_js:
  - '6.11.5'

cache:
  yarn: true
  directories:
     - ./node_modules

before_install:
  - echo -e "repo_token: $REPO_TOKEN" >> ~/.coveralls.yml

before_script:
  - npm install -g --silent @angular/cli
  - npm install -g --silent yarn
  - yarn install

script:
  - npm run lint
  - npm run build:electron
